### ISSUE TITLE
TypeError: 'int' object is not iterable

### ISSUE THREAD

**Issue by ghost** [TrayserCassa/DiscordHandler#5]
--- Logging error ---
Traceback (most recent call last):
  File "/home/fluorescentbacon/.local/lib/python3.7/site-packages/discord_handler/DiscordHandler.py", line 65, in emit
    for user in self._notify_users:
TypeError: 'int' object is not iterable
Call stack:
  File "main.py", line 108, in <module>
    bot.run(TOKEN)
  File "/home/fluorescentbacon/.local/lib/python3.7/site-packages/discord/client.py", line 708, in run
    loop.run_forever()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 539, in run_forever
    self._run_once()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 1775, in _run_once
    handle._run()
  File "/usr/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/home/fluorescentbacon/.local/lib/python3.7/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "main.py", line 79, in on_ready
    logger.info("We have logged in.")
  File "/usr/lib/python3.7/logging/__init__.py", line 1383, in info
    self._log(INFO, msg, args, **kwargs)
  File "/usr/lib/python3.7/logging/__init__.py", line 1519, in _log
    self.handle(record)
  File "/usr/lib/python3.7/logging/__init__.py", line 1529, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.7/logging/__init__.py", line 1591, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python3.7/logging/__init__.py", line 905, in handle
    self.emit(record)
  File "/home/fluorescentbacon/.local/lib/python3.7/site-packages/discord_handler/DiscordHandler.py", line 70, in emit
    self.handleError(record)

**Comment by TrayserCassa** [comment]
so you set your notify_users to an integer. This will fail.

You set the notify_users like this:
DiscordHandler(webhook_url, agent, notify_users=12)

But you need to set it as a list:
DiscordHandler(webhook_url, agent, notify_users=['username'])

@fluorescentb
